---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/main.yml"

- include: create-teamcity-user.yml
  when: install_teamcity
- include: mysql-connector.yml
  when: "teamcity_server_db_type == 'mysql' and install_teamcity"
- include: teamcity-server.yml
  when: install_teamcity
- include: configure-teamcity.yml
  when: configure_teamcity
- include: install-plugins.yml
  when: configure_teamcity
- include: license.yml
  when: configure_teamcity
- include: enable_agent.yml
  when: configure_teamcity
