---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/main.yml"

- include: create-teamcity-user.yml
- include: mysql-connector.yml
  when: "teamcity_server_db_type == 'mysql'"
- include: teamcity-server.yml
- include: install-plugins.yml
- include: license.yml
