---
- name: "Get distribution"
  get_url:
    url: "http://download.jetbrains.com/teamcity/TeamCity-{{ teamcity_server_version }}.tar.gz"
    dest: "/tmp/TeamCity-{{ teamcity_server_version }}.tar.gz"
    validate_certs: no
    timeout: 60
    checksum: "sha256:{{ teamcity_server_sha256 }}"
  register: _teamcity_package

- name: "Add TeamCity service default config"
  template:
    src: "teamcity-server.j2"
    dest: "/etc/default/teamcity-server"
    mode: 0644

- name: "Put TeamCity service file"
  template:
    src: "{{ teamcity_service_source }}"
    dest: "{{ teamcity_service_target }}"
    mode: 0644

- name: "Stop TeamCity Server before upgrade"
  service:
    name: teamcity-server
    state: stopped
  when: _teamcity_package|changed

- name: "Ensure that upgrade will not fail"
  file:
    path: "{{ teamcity_server_dir }}/webapps"
    state: absent
  when: _teamcity_package|changed

- name: "Unpack distribution"
  unarchive:
    src: "/tmp/TeamCity-{{ teamcity_server_version }}.tar.gz"
    dest: "{{ teamcity_server_install_dir }}"
    owner: "{{ teamcity_server_user }}"
    group: "{{ teamcity_server_group }}"
    copy: "no"

- name: "Create dir structure"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ teamcity_server_user }}"
    group: "{{ teamcity_server_group }}"
    mode: 0755
  with_items:
    - "{{ teamcity_server_dir }}/logs"
    - "{{ teamcity_server_config_dir }}"
